### ISSUE TITLE
Add examples to documentation

### ISSUE THREAD

**Issue by rubikitch** [GuiltyDolphin/monitor#5]
I am interested in your package to monitor expression for debug.
But I cannot find any actual examples.
I have read monitor.el but I have no idea how to use it.

**Comment by GuiltyDolphin** [comment]
@rubikitch The documentation is currently a WIP as I work out any API issues and implement the 'low-level' monitors.

The Org documentation is here: https://github.com/GuiltyDolphin/monitor/blob/master/doc/monitor.org

From line 359 onwards are monitor definitions: https://github.com/GuiltyDolphin/monitor/blob/2249c9cb2f36bbec3ef175c69e59b180b54be13f/monitor.el#L359

There's a couple of examples of use in org-evil: https://github.com/GuiltyDolphin/org-evil/blob/f9b5f84a36a4d2fd703950aaa6e413fae36bb688/org-evil-core.el#L72

Thanks for pointing this out, I'll bump examples up as a priority in the docs.

**Comment by GuiltyDolphin** [comment]
@rubikitch I've added an initial example to the documentation (I'll add more in the future), let me know if you have any more issues!
